### ISSUE TITLE
scrapper is broken for new users

### ISSUE THREAD

**Issue by SpEcHiDe** [SpEcHiDe/MyTelegramOrgRoBot#3]
[ERRED_PAGE](https://github.com/SpEcHiDe/MyTelegramOrgRoBot/blob/master/translation.py#L17) seems to appear, when trying to get the APP ID for new user sign ups..!

**Comment by SpEcHiDe** [comment]
hmmm 167

**Comment by SpEcHiDe** [comment]
if anybody else is able to reproduce this, please help me by telling what is wrong with the scrapper 😖😖☹️

**Comment by SpEcHiDe** [comment]
looks like it is broken from Telegram side, the fix is simple, but I cant do it currently. 
Let me wait for Telegram reply, or I will "fix" it after some days. :\

**Comment by SpEcHiDe** [comment]
917989 again :\

**Comment by mbeiranvand** [comment]
# ~~[]()****~~

**Comment by SpEcHiDe** [comment]
fixed in beta branch,

**Comment by ByeCoder** [comment]
Hello
I think there is a problem still for creating new application.It just returns ERROR

**Comment by SpEcHiDe** [comment]
Did you try with https://t.me/useTGxBot ?

**Comment by ByeCoder** [comment]
Yes.
This is result...
```
something wrongings. failed to get app id. 

@SpEcHlDe
```

It just happen for new accounts

**Comment by SpEcHiDe** [comment]
Ok, will see 😐🤔
